/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankingapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    public void testCreateAccount(){
        //Initialize test data
        String firstName = "John";
        String lastName = "Doe";

        //Method to create account
        CreateAccount account = new CreateAccount();

        //Test generating account number
        account.setAccountNumber();

        //Validate account number
        String accountNum = account.getAccountNumber();

        //Test setting PIN number
        account.setPinNumber();

        //Validate PIN number
        int pin = account.getPinNumber();

        //Ensure the generated PIN number is within pin >=1000 && pin <= 9999
        assertTrue(pin >= 1000 && pin <= 9999);

        //Ensure PIN is a 4 digit number
        assertEquals(4, String.valueOf(pin).length());

        //Asserts
        assertNotNull(accountNum);
        assertTrue(CreateAccount.luhnsAlgorithmCheck(accountNum));
    }

    @Test
    public void testLuhnsAlgorithmValid(){
        //Test an actual number already passing luhns algorith check
        assertTrue(CreateAccount.luhnsAlgorithmCheck( "502091324785"));
    }

    @Test
    public void testLuhnsAlgorithmInvalid(){
        //Test an invalid number
        assertFalse(CreateAccount.luhnsAlgorithmCheck( "1234567891234"));
    }

}
