/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankingapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    public void testCreateAccount(){
        //Initialize test data
        String firstName = "John";
        String lastName = "Doe";

        //Method to create account
        CreateAccount account = new CreateAccount();

        //Generate account number
        account.setAccountNumber();

        //Validate
        String accountNum = account.getAccountNumber();

        //Asserts
        assertNotNull(accountNum);
        assertTrue(CreateAccount.luhnsAlgorithmCheck(accountNum));
    }
}
